### ISSUE TITLE
Assertion Error:

### ISSUE THREAD

**Issue by adrianliaw** [agilearning/BusinessCards#13]
這邊提醒一下 `is` 是比對兩個object的id 在python裡面有時候兩個一樣的string的id會一樣有時候不會 數字也是 不要問我為什麼因為我也不知道 所以改成`==`吧~ 不然assert會噴錯

**Comment by c3h3** [comment]
感謝 Adrian 大大 (跪)

**Comment by suensummit** [comment]
讚嘆 Adrian :+1:
