### ISSUE TITLE
NameError:

### ISSUE THREAD

**Issue by adrianliaw** [agilearning/BusinessCards#20]
`NameError: name 'agilearning' is not defined`
在info function裡面有一個`assert agilearning.VAT_ID == 24755908`  
不過因為在import的時候只有 `from agilearning import agilearner`  
所以`agilearning`沒有被import進來 應該改成下面這樣嗎?

``` python
from agilearning import agilearner, VAT_ID
...
@agilearner
def adrianliaw(**my):
    ....
    assert VAT_ID == 24755908
```

**Comment by suensummit** [comment]
好喔，這樣才跑得過對吧？我來改過一輪 :+1:

**Comment by adrianliaw** [comment]
感恩Summit 讚嘆Summit
